config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, controllers: {registrations: 'registrations'}

  root 'static_pages#index'

  get 'dashboard' => 'dashboard#index'

  resources :items
  resources :product_images

  resources :image_uploads, only: :destroy

  resources :item_selections, only: [:new, :create]
  resources :company_selections, only: [:new, :create]

  resources :appointment_requests do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :companies
  resources :appointment_approvals, only: :create
  resources :appointment_declinals, only: :create

  resources :charges

  resources :company_users, only: [:new, :create]

  resources :item_statuses, only: :update

  resources :users, only: :show

  get 'privacy_policy' => 'static_pages#privacy_policy'
  get 'terms_and_conditions' => 'static_pages#terms_and_conditions'
  

end

app/models/appointment_request.rb
class AppointmentRequest < ActiveRecord::Base
  belongs_to :company, counter_cache: true
  belongs_to :user, counter_cache: true

  has_many :comments, dependent: :destroy
  has_many :appointment_items, dependent: :destroy
  has_many :items, through: :appointment_items
  has_many :read_statuses, dependent: :destroy

  validates :company_id, :user_id, :start_time, :end_time, presence: true
  validate :start_must_be_before_end_time

  private

  def start_must_be_before_end_time
      errors.add(:start_time, "must be before end time") unless start_time < end_time
  end 
end

app/controllers/appointment_requests_controller.rb
class AppointmentRequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_invalid_date, only: :create

  def index
    @appointment_requests = current_user.appointment_requests.order(start_time: :asc)
    @incoming_requests = AppointmentRequest.where(company_id: current_user.company_id).order(start_time: :asc)
  end

  def show
    @appointment_request = AppointmentRequest.find(params[:id])
    @company = Company.find(@appointment_request.company_id)
    @appointment_items = @appointment_request.appointment_items
    @comments = @appointment_request.comments.order(updated_at: :desc)
    @user = User.find(@appointment_request.user_id)

    @read_status ||= ReadStatus.find_by(user_id: current_user.id, appointment_request_id: @appointment_request.id)

    return @read_status.touch(:read_on) if @read_status
    current_user.read_statuses.create(appointment_request_id: @appointment_request.id, read_on: DateTime.now)      
  end

  def new
    @company = Company.find(params[:company_id])
    @items = []
    params[:item_ids].split(",").each{|item_id| @items.push(Item.find(item_id)) } # push all item objects into array
  end

  def create
    params[:appointment_request][:end_time] = (DateTime.parse(params[:appointment_request][:start_time]) + 30.minutes).strftime('%Y-%m-%d %k:%M')
    @appointment_request = AppointmentRequest.create(appointment_request_params)
    if @appointment_request.save
      params[:items].each{ |item| @appointment_request.appointment_items.create(item_id: item) } # create appointment item objects for each item
      redirect_to appointment_requests_path
    else
      flash[:danger] = @appointment_request.errors.full_messages[0]
      redirect_to :back
    end
  end

  private

  def check_invalid_date
    begin
      DateTime.parse(params[:appointment_request][:start_time])
    rescue
      flash[:danger] = "Invalid date"
      redirect_to :back
    end
  end

  def appointment_request_params
    params.require(:appointment_request).permit(:company_id, :user_id, :start_time, :end_time, :approved, :declined, :sched_date_field, :sched_time_field)
  end
end

app/helpers/appointment_requests_helper.rb
module AppointmentRequestsHelper
  def item_status(item)
    if item.status == AppointmentItem::STATUS[0]
      '<i class="fa fa-clock-o"></i> '.html_safe + AppointmentItem::STATUS[0]
    elsif item.status == AppointmentItem::STATUS[1]
      '<i class="fa fa-check" style="color:#29AFE7"></i> '.html_safe + AppointmentItem::STATUS[1]
    elsif item.status == AppointmentItem::STATUS[2]
      '<i class="fa fa-minus-circle" style="color:red"></i> '.html_safe + AppointmentItem::STATUS[2]
    elsif item.status == AppointmentItem::STATUS[3]
      '<i class="fa fa-list" style="color:#34495E"></i> '.html_safe + AppointmentItem::STATUS[3]
    elsif item.status == AppointmentItem::STATUS[4]
      '<i class="fa fa-usd" style="color:#5CB85C"></i> '.html_safe + AppointmentItem::STATUS[4]
    end


  end

  def status(incoming_request)
    if incoming_request.approved 
      "Approved" 
    elsif incoming_request.declined 
      "Declined" 
    else 
      "Waiting" 
    end
  end

  def status_icon(incoming_request)
    if incoming_request.approved 
      '<i class="fa fa-check-circle" style="color:#05CE05;"></i>'.html_safe
    elsif incoming_request.declined 
      '<i class="fa fa-times-circle" style="color:#D9534F"></i>'.html_safe
    else 
      '<i class="fa fa-hourglass-half"></i>'.html_safe
    end

  end
end

app/views/appointment_requests/_comments.html.erb
<h1>Chat</h1>

<%= simple_form_for Comment.new, url: appointment_request_comments_path(appointment_request_id: params[:id]), method: :post do |f| %>
  <%= f.input :text %>
  <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
  <%= f.submit 'Submit', class: 'btn btn-success btn-block', data: { disable_with: 'Submitted' } %>
<% end %>

<hr>
<% @comments.each do |comment| %>
  <% user = User.find(comment.user_id) %>
  <div class="row">
    <div class="col-xs-3">
      <span class="pull-left"><small><%= image_tag user.photo.thumb.url, class: 'img_circle_sm' %><%= fullname(user) %></small></span>
      <br>
      <br class="clearfix">
      
    </div>
    <div class="col-xs-9">
      <p><%= comment.text %></p>
    </div>
    <p><span class="pull-right"><small>at <%= comment.created_at.strftime('%m/%d %T') %></small></span></p>
  </div>
  
  <br class="clearfix">
  <hr>
<% end %>

app/views/appointment_requests/index.html.erb
<% if current_user.is_company_account? %>

  <h1>Incoming Appointment Requests</h1>
  <hr>
  <h3><%= "There are no incoming requests at this time." if @incoming_requests.empty? %></h3>
  <div class="row">
    <% @incoming_requests.each do |incoming_request| %>
    <div class="col-xs-12 col-md-4">

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3><%= unread(incoming_request) %> <%= Company.find(incoming_request.company_id).name %>
            <span class="pull-right"><%= status_icon(incoming_request) %></span>
            </h3>
        </div>
        <div class="panel-body">
          <ul style="list-style-type:none;padding-left:0px;">
            <li><strong>Start Time:</strong> <%= display_datetime(incoming_request.start_time) %></li>
            <li><strong>End Time:</strong> <%= display_datetime(incoming_request.end_time) %></li>
            <li><strong>Status:</strong> <%= status(incoming_request) %></li>
          </ul>
          <%= link_to 'Details', appointment_request_path(incoming_request), class: 'btn btn-danger btn-block' %>
          <%= link_to 'Accept', appointment_approvals_path(appointment_request_id: incoming_request.id), method: :post, class: 'btn btn-success btn-block' unless incoming_request.approved || incoming_request.declined %>
          <%= link_to 'Decline', appointment_declinals_path(appointment_request_id: incoming_request.id), method: :post, class: 'btn btn-warning btn-block' unless incoming_request.approved || incoming_request.declined %>
          <%= "<button class='btn btn-success btn-block'><i class='fa fa-check-circle'></i> Approved!</button>".html_safe if incoming_request.approved %>

        </div>
      </div>

    </div>
    <% end %>
  </div>

<% else %>

  <h1>My Appointments</h1>
  <%= link_to ('<i class="fa fa-calendar"></i> Schedule New Appointment').html_safe, new_item_selection_path %>
  <hr>
  <h3><%= "You have no appointments at this time. Click <a href='/item_selections/new'>here</a> to make a new appointment request.".html_safe if @appointment_requests.empty? %></h3>
  <div class="row">
    <% @appointment_requests.each do |appointment_request| %>
      <div class="col-xs-12 col-md-4">

        <div class="panel panel-default">
          <div class="panel-heading">
            <h3><%= unread(appointment_request) %><%= Company.find(appointment_request.company_id).name %>
              <span class="pull-right"><%= status_icon(appointment_request) %></span>
              </h3>
          </div>
          <!-- panel-heading -->
          <div class="panel-body">
            <ul style="list-style-type:none;padding-left:0px;">
              <li><strong>Start Time:</strong> <%= display_datetime(appointment_request.start_time) %></li>
              <li><strong>End Time:</strong> <%= display_datetime(appointment_request.end_time) %></li>
              <li><strong>Status:</strong> <%= status(appointment_request) %></li>
            </ul>
            <%= link_to 'Details', appointment_request_path(appointment_request), class: 'btn btn-danger btn-block' %>
          </div>
          <!-- panel-body -->
        </div>
        <!-- panel pane-default -->

      </div>
      <!-- col-xs-12 col-md-4 -->
    <% end %>
    <!-- @appointment_requests.each -->
  </div>
  <!-- row -->

<% end %>
<!-- if current_user.company_id -->

app/views/appointment_requests/new.html.erb
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

<h1>Appointment for <%= @company.name %></h1>

<div class="scrollable well" style="max-height:50vh;">
  <h3>Your Items</h3>
  <% @items.each do |item| %>

    <% product_image = ProductImage.find_by(item_id: item.id) %>

    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">

          <div class="col-xs-4 col-sm-2">
            <div class="thumbnail">
              <% if product_image.nil? %>
                <%= image_tag 'shirt.png', class: 'item_image_sm' %>
              <% else %>
                <%= image_tag product_image.photo.thumb.url, class: 'item_image' %>
              <% end %>
            </div>
          </div>

          <div class="col-xs-8 col-sm-10">
            <%= render partial: "items/card", locals: {item: item} %>
          </div>

        </div>
      </div>
    </div>
  <% end %>
</div>

<h2>Please enter your requested start time.</h2>
<div class="col-xs-12 col-md-6">
<%= simple_form_for AppointmentRequest.new, url: appointment_requests_path(items: @items), method: :post do |f| %>
  <%= f.input :start_time, :as => :datetime_picker, label: "Requested Start Time" %>
  <%= f.input :company_id, as: :hidden, input_html: { value: @company.id } %>
  <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
  <%= f.submit 'Submit', class: 'btn btn-success btn-lg btn-block', data: { disable_with: "Please wait..." } %>
<% end %>
</div>

app/views/appointment_requests/show.html.erb
<h1>Appointment for <%= @company.name %></h1>
<hr>

<div class="row">

  <div class="col-xs-12 col-md-4">
    <div class="well">
      <div class="row profile_container">
        <div class="col-xs-4">
          <%= image_tag @company.photo, class: 'item_image_sm img_circle' %>
        </div>
        <div class="col-xs-8">
          <h5><%= @company.name %></h5>
        </div>
      </div>
      <!-- row -->

      <div class="row profile_container">
        <div class="col-xs-4">
          <%= image_tag @user.photo, class: 'item_image_sm img_circle' %>
        </div>
        <div class="col-xs-8">
          <h5><%= link_to fullname(@user), user_path(@user) %></h5>
        </div>
      </div>
      <!-- row -->
    </div>
    <!-- well -->

    <div class="well">
      <h3><i class="fa fa-calendar"></i> Appointment Details</h3>
      <ul style="list-style-type:none;padding-left:0px;">
        <li><strong>Start Time:</strong> <%= display_datetime(@appointment_request.start_time) %></li>
        <li><strong>End Time:</strong> <%= display_datetime(@appointment_request.end_time) %></li>
        <li><strong>Status:</strong> <%= status(@appointment_request) %></li>
      </ul>
    </div>
    <!-- well -->

    <div class="well">
      <%= render partial: "companies/details", locals: {company: @company} %>
    </div>
    <!-- well -->
  </div>
  <!-- col-md-4 -->

  <div class="col-xs-12 col-md-8">
    <h1><i class="fa fa-comment"></i> Messages</h1>

    <%= simple_form_for Comment.new, url: appointment_request_comments_path(appointment_request_id: params[:id]), method: :post do |f| %>
      <%= f.input :text, label: false, placeholder: "Enter message here" %>
      <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
      <%= f.submit 'Send', class: 'btn btn-success btn-block', data: { disable_with: 'Submitted' } %>
    <% end %>

    <hr>

    <div class="scrollable">
      <% @comments.each do |comment| %>
        <% user = User.find(comment.user_id) %>
        <div class="row">
          <div class="col-xs-3">
            <span class="pull-left"><small><%= image_tag user.photo.thumb.url, class: 'img_circle_sm' %><%= fullname(user) %></small></span>
            <br>
            <br class="clearfix">
          </div>
          <!-- col-xs-3 -->

          <div class="col-xs-9">
            <p><%= comment.text %></p>
          </div>
          <!-- col-xs-9 -->

          <p>
            <span class="pull-right"><small>at <%= comment.created_at.strftime('%m/%d %T') %></small></span>
          </p>
        </div>
        <!-- row -->
        
        <br class="clearfix">
        <hr>
      <% end %>
      <!-- end of comments loop -->
    </div>
    <!-- scrollable -->

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3><i class="fa fa-list"></i> Items</h3>
      </div>
      <!-- panel-heading -->

      <div class="scrollable">
        <% @appointment_items.each do |appointment_item| %>
          <% item = Item.find(appointment_item.item_id) %>
          

            <div class="panel-body">
              <div class="row">

                <div class="col-xs-2">
                  <div class="thumbnail">
                    <% if item.product_images.empty? %>
                      <%= image_tag 'shirt.png', class: 'item_image_sm' %>
                    <% else %>
                      <%= image_tag ProductImage.find_by(item_id: item.id).photo.thumb.url, class: 'item_image' %>
                    <% end %>
                  </div>
                  <%= link_to 'View Item', item_path(item) %>
                </div>

                <div class="col-xs-10">
                  <%= render partial: "items/card", locals: {item: item} %>
                  <% appointment_item = AppointmentItem.find_by(item_id: item, appointment_request_id: @appointment_request.id) %>
                  <% if current_user.company_id == @appointment_request.company_id %>
                    <div class="row">
                      <div class="col-xs-12">
                        <!-- accept-charset="UTF-8" action="/item_statuses/<%= item.id %>?appointment_request_id=<%= @appointment_request.id %>" class="simple_form edit_appointment_item" data-remote="true" id="edit_appointment_item_11" method="post" name="edit_appointment_item_11" novalidate="novalidate" -->
                        <form id="edit_appointment_item_<%= appointment_item.id %>">
                          <input name="utf8" type="hidden" value="✓">
                          <input type="radio" name="status_<%= appointment_item.id %>" data-labelauty="Pending|Pending" <%= checked(appointment_item, "Pending") %>>
                          <input type="radio" name="status_<%= appointment_item.id %>" data-labelauty="Accepted|Accepted" <%= checked(appointment_item, "Accepted") %>>
                          <input type="radio" name="status_<%= appointment_item.id %>" data-labelauty="Declined|Declined" <%= checked(appointment_item, "Declined") %>>
                          <input type="radio" name="status_<%= appointment_item.id %>" data-labelauty="On Display|On Display" <%= checked(appointment_item, "On Display") %>>
                          <input type="radio" name="status_<%= appointment_item.id %>" data-labelauty="Sold|Sold" <%= checked(appointment_item, "Sold") %>>
                          <div class="form-group hidden appointment_item_item_id">
                              <input class="hidden form-control form-control" id="appointment_item_item_id" name="appointment_item[item_id]" type="hidden" value="<%= item.id %>">
                          </div>
                          <div class="form-group hidden appointment_item_appointment_request_id">
                              <input class="hidden form-control form-control" id="appointment_item_appointment_request_id" name="appointment_item[appointment_request_id]" type="hidden" value="<%= @appointment_request.id %>">
                          </div>
                      </form>


                        

                        <script type="text/javascript">
                          $('#edit_appointment_item_<%= appointment_item.id %>').change(function(){
                            $.ajax({
                              url: '/item_statuses/<%= appointment_item.id %>?appointment_request_id=<%= @appointment_request.id %>',
                              type: 'PUT',
                              data: $('#edit_appointment_item_<%= appointment_item.id %>').serialize(),
                              success: function(data) {

                              }
                            });
                          });
                        </script>
                      </div>
                      <!-- col-xs-12 col-md-2 -->
                    </div>
                    <!-- row -->
                  <% else %>
                    <p class="pull-right"><strong><%= item_status(appointment_item) %></strong></p>
                  <% end %>
                </div>
                <!-- col-xs-10 -->
              </div>
              <!-- row -->
            </div>
            <!-- panel body -->
            <hr>
        <% end %>
        <!-- end loop -->
      </div>
      <!-- scrollable -->
    </div>
    <!-- panel-default -->
  </div>
  <!-- col-md-8 -->
</div>
<!-- row -->

<script type="text/javascript">
$(document).ready(function(){
    $(":radio").labelauty();
});
</script>