config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, controllers: {registrations: 'registrations'}

  root 'static_pages#index'

  get 'dashboard' => 'dashboard#index'

  resources :items
  resources :product_images

  resources :image_uploads, only: :destroy

  resources :item_selections, only: [:new, :create]
  resources :company_selections, only: [:new, :create]

  resources :appointment_requests do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :companies
  resources :appointment_approvals, only: :create
  resources :appointment_declinals, only: :create

  resources :charges

  resources :company_users, only: [:new, :create]

  resources :item_statuses, only: :update

  resources :users, only: :show

  get 'privacy_policy' => 'static_pages#privacy_policy'
  get 'terms_and_conditions' => 'static_pages#terms_and_conditions'
  

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def index
    
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<br>

<% if current_user.is_company_account? && current_user.company_id.nil? %>
  <p class="alert alert-info alert-dismissible"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>It looks like you haven't entered your company information yet. Click <%= link_to 'here', new_company_path, style: 'color:#D9534F; text-decoration: underline;' %> to create your company.</p>
<% end %>

<div class="row">

  <% if current_user.is_company_account? %>
    <div class="col-xs-12 col-md-6">

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">My Company</h3>
        </div>
        <div class="panel-body panel-body-dashboard">
          <div class="well panel_well">
            <h3 class="text-center"><i class="fa fa-pencil"></i> Review and Edit Company</h3>
          </div>
        </div>
        <!-- panel-body -->
        <div class="panel-footer">
          <%= link_to ('<i class="fa fa-list"></i> My Company').html_safe, company_path(current_user.company_id), class: 'btn btn-success center-block' if current_user.company_id %>
          <%= link_to ('<i class="fa fa-list"></i> My Company').html_safe, '#', class: 'btn btn-success center-block', disabled: true unless current_user.company_id %>
        </div>
        <!-- panel footer -->
      </div>
      <!-- panel -->

    </div>
    <!-- col-xs-12 col-md-6 -->

  <% else %>


    <div class="col-xs-12 col-md-6">

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">My Items</h3>
        </div>
        <div class="panel-body panel-body-dashboard">
          <div class="well panel_well">
            <h3 class="text-center"><i class="fa fa-pencil"></i> Review, Edit, or Delete Items</h3>
          </div>
        </div>
        <!-- panel-body -->
        <div class="panel-footer">
          <%= link_to ('<i class="fa fa-list"></i> My Items').html_safe, items_path, class: 'btn btn-success center-block' %>
        </div>
        <!-- panel footer -->
      </div>
      <!-- panel -->

    </div>
    <!-- col-xs-12 col-md-6 -->

  <% end %>

  <div class="col-xs-12 col-md-6">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">My Appointments</h3>
      </div>
      <div class="panel-body panel-body-dashboard">
        <div class="well panel_well">
          <h3 class="text-center"><i class="fa fa-coffee"></i> Review, Reschedule, or Delete Appointments</h3>
        </div>
      </div>
      <div class="panel-footer">
        <%= link_to ('<i class="fa fa-calendar-check-o"></i> My Appointments').html_safe, appointment_requests_path, class: 'btn btn-danger center-block' unless current_user.is_company_account? && current_user.company_id.nil? %>
        <%= link_to ('<i class="fa fa-calendar-check-o"></i> My Appointments').html_safe, appointment_requests_path, class: 'btn btn-danger center-block', disabled: true if current_user.is_company_account? && current_user.company_id.nil? %>
      </div>
    </div>
    <!-- panel -->

  </div>
  <!-- col-xs-12 col-md-6 -->

</div>
<!-- row -->

<% unless current_user.is_company_account? %>
<div class="row">
  <div class="col-xs-12 col-md-6">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Upload Items</h3>
      </div>
      <div class="panel-body panel-body-dashboard">
        <div class="row">
          <div class="col-xs-12 col-md-4">
            <div class="well panel_well_sm">
              ① Upload Item Photos
            </div>
            <!-- well -->
          </div>
          <!-- col-xs-4 -->

          <div class="col-xs-12 col-md-4">
            <div class="well panel_well_sm">
              ② Enter Description
            </div>
            <!-- well -->
          </div>
          <!-- col-xs-4 -->

          <div class="col-xs-12 col-md-4">
            <div class="well panel_well_sm">
              ③ Select Done
            </div>
            <!-- well -->
          </div>
          <!-- col-xs-4 -->

        </div>
        <!-- row -->
      </div>
      <div class="panel-footer">
        <%= link_to ('<i class="fa fa-plus-circle"></i> Upload Items').html_safe, new_product_image_path, class: 'btn btn-primary center-block' %>
      </div>
    </div>
    <!-- panel -->

  </div>
  <!-- col-xs-12 col-md-6 -->

  <div class="col-xs-12 col-md-6">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Schedule Appointment</h3>
      </div>
      <div class="panel-body panel-body-dashboard">
        <div class="row">
          <div class="col-xs-12 col-md-4">
            <div class="well panel_well_sm">
              ① Select Items for Store
            </div>
            <!-- well -->
          </div>
          <!-- col-xs-4 -->

          <div class="col-xs-12 col-md-4">
            <div class="well panel_well_sm">
              ② Request Appointment Date
            </div>
            <!-- well -->
          </div>
          <!-- col-xs-4 -->

          <div class="col-xs-12 col-md-4">
            <div class="well panel_well_sm">
              ③ Submit Items Request
            </div>
            <!-- well -->
          </div>
          <!-- col-xs-4 -->

        </div>
        <!-- row -->
      </div>
      <div class="panel-footer">
        <%= link_to ('<i class="fa fa-calendar"></i> Schedule Appointment').html_safe, new_item_selection_path, class: 'btn btn-warning center-block' %>
      </div>
    </div>
    <!-- panel -->

  </div>
  <!-- col-xs-12 col-md-6 -->

</div>
<!-- row -->
<% end %>
<!-- unless current_user.company_id  -->