config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, controllers: {registrations: 'registrations'}

  root 'static_pages#index'

  get 'dashboard' => 'dashboard#index'

  resources :items
  resources :product_images

  resources :image_uploads, only: :destroy

  resources :item_selections, only: [:new, :create]
  resources :company_selections, only: [:new, :create]

  resources :appointment_requests do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :companies
  resources :appointment_approvals, only: :create
  resources :appointment_declinals, only: :create

  resources :charges

  resources :company_users, only: [:new, :create]

  resources :item_statuses, only: :update

  resources :users, only: :show

  get 'privacy_policy' => 'static_pages#privacy_policy'
  get 'terms_and_conditions' => 'static_pages#terms_and_conditions'
  

end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :user, counter_cache: true
  has_many :product_images, dependent: :destroy
  has_many :appointment_items, dependent: :destroy
  has_many :appointment_reqeusts, through: :appointment_items

  validates_presence_of :brand, :category, :color, :condition, :description, :image_upload_id, :gender, :material
  validates_presence_of :size, :if => :is_not_suit?

  GENDERS = ["Men's", "Women's"]

  CONDITION = ["New", "Like New", "Very Good", "Good", "Fair"]

  WOMENS_CATEGORIES = ["Dress", "Skirt", "Shirt", "Blouse", "Sweater", "Outerwear", "Denim", "Active Wear", "Pants", "Shorts", "Suits", "Blazer", "Swimwear", "Shoes", "Bags", "OTHER"]

  WOMENS_BAG_CATEGORIES = ["Handbags", "Shoulder Bags & Hobos", "Totes", "Satchel", "Clutches", "Crossbody", "Backpacks", "Wristlets", "OTHER"]

  WOMENS_SHOE_CATEGORIES = ["Sandals", "Boots", "Booties", "Flats", "Heels & Pumps", "Wedges", "Slippers", "Athletic", "Loafers", "Clogs"]

  WOMENS_SIZES = ["XXS", "XS", "S", "M ", "L", "XL", "XXL", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "0P", "2P", "4P", "6P", "8P", "10P", "12P", "14P", "16P", "28", "30", "32", "34", "36", "38", "40", "42", "44", "OTHER"]

  WOMENS_SHOE_WIDTH = ["Narrow", "Medium", "Wide"]

  WOMENS_SHOE_SIZES = ["6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12"]

  WOMENS_APPAREL_MATERIALS = ["Leather", "Suede", "Silk", "Cotton", "Rayon", "Wool", "Linen", "Rayon", "Nylon", "Polyester", "Acrylic"]

  WOMENS_SHOE_MATERIALS = ["Canvas", "Leather ", "Faux Leather", "Suede", "Hemp", "OTHER"]

  WOMENS_APPAREL_BRANDS = ["ABS by Allen B. Schwartz", "Adrianna Papell", "Alice + Olivia", "Anne Klein", "Badgley Mischka", "BCBG", "BCBGeneration", "BOSS Hugo Boss", "Catherine Catherine ", "Cynthia Rowley", "Diane von Furstenberg", "Elie Tahari", "Ella Moss", "ESCADA", "Free People", "French Connection", "Halston Heritage", "J.McLaughlin", "joan vass", "Julie Brown", "Karen Millen", "Kay Unger", "Lafayette", "New York", "Lafayette", "New York Petites", "New York Plus", "Laundry", "Lilla ", "Lucy Paris", "Mara Hoffman", "Marc New York", "Max Mara", "Melly M", "Mink Pink", "Mott 50", "Nicole Miller", "Olivaceous", "Parker", "Pink Tartan", "Rachel Zoe", "Rebecca Minkoff", "Rebecca Taylor", "Shoshanna", "Single", "Soft Joie", "SOUTHERN fROCK", "Splendid", "Sue Wong", "susana Monaco", "T Tahari", "Tahari by Arthur S. Levine", "TART", "Taylor", "Theory", "Three Dots", "Tocca", "Tommy Bahama", "Tori Richard", "Tory Burch", "TOWNSEN", "Trina Turk", "YAL NY ", "Young Fabulous & Broke", "YUMMI", "OTHER"]

  WOMENS_HANDBAG_BRANDS = ["Bottega Veneta", "Burberry", "Celine", "Chanel", "Chloe", "Coach", "Cole Haan", "FENDI", "Furla", "Givenchy", "Gucci", "Hermes", "Jimmy Choo", "Judith Leiber Couture", "kate spade new York", "LANVIN", "Longchamp", "Louis Vuitton", "Miu Miu", "Prada", "Saint Laurent", "Salvatore Ferragamo", "Stella McCartney", "Tod's", "Valentino", "Yves Saint Laurent", "OTHER "]

  WOMENS_SHOE_BRANDS = ["andrew stevens", "Arche", "Ash", "BCBGeneration", "Belle", "Bettye Muller", "Carolinna Espinosa", "Charles by Charles David", "Charles David", "Clarks", "Cole Haan", "Dolce Vita", "Donald J Pliner", "Elie Tahari", "Franco Sarto", "French Connection", "Giuseppe Zanotti", "Halston Heritage", "Isola", "Ivanka Trump", "Jack Rogers", "Jimmy Choo", "JOE'S Jeans", "Joie", "Kay Unger", "L.K.Bennett", "Latigo", "Lucky Brand", "Marc Fisher", "New Balance", "Nisolo", "Dr.  Scholl's Collection", "Prada", "PUMA", "Rachel Zoe", "Rebecca Minkoff", "Rockport", "Saint Laurent", "Salvatore Ferragamo", "SeaVees", "Sesto Meucci", "Seychelles", "Sperry", "Steven By Steve Madden", "Tahari", "Tod's", "Tommy Bahama", "Tretorn", "Trina Turk", "UGG", "Valentino", "Vaneli", "Via Spiga", "Vince", "Vince Camuto", "Yves Saint Laurent", "OTHER"]

  MENS_CATEGORIES = ["Shirts", "Outerwear", "Suits", "Sport Coats", "Sweaters & Hoodies", "Denim", "Active Wear", "Pants", "Polos & Tees", "Shoes", "Shorts", "Swimwear", "OTHER"]

  MENS_SHIRT_SIZES = ["S", "M", "L", "XL", "XXL", "XXXL", "15", "15.5", "16", "16.5", "17", "17.5", "18", "18.5", "19", "19.5", "20", "OTHER "]

  MENS_SLEEVE_LENGTH = ["32", "32/33", "33", "33/34", "34", "34/35", "35", "35/36", "36", "36/37", "37", "37/38", "38", "OTHER"]

  MENS_PANTS_SIZES = ["26", "28", "30", "32", "34", "36", "38", "40", "42", "44", "46", "XXS", "XS", "S", "M", "L", "XL", "XXL", "OTHER"]

  MENS_INSEAM_LENGTH = ["Short", "Regular", "Long"]

  MENS_JACKET_SIZES = ["38", "40", "42", "44", "46", "48", "50", "52", "54", "56"]

  MENS_SUIT_LENGTH = ["Short", "Regular", "Long", "X-Long"]

  MENS_APPAREL_BRANDS = ["Ben Sherman", "Borgo", "Brooks Brothers", "English Laundry", "Forsyth of Canada", "HIHO", "HUDSON", "Hugo Boss", "Ike Behar", "J.McLaughlin", "JOE'S", "John Varvatos", "JOHNNIE-O7", "Maker & Company", "Report Collection", "Robert Graham", "Seven For All Mankind", "Southern Tide", "Splendid Mills", "Theory", "Vince Camuto", "vineyard vines", "WRK17", "OTHER"]

  MENS_APPAREL_MATERIALS = ["Leather", "Suede", "Silk", "Cotton", "Denim", "Wool", "Linen", "OTHER"]

  MENS_SHOE_CATEGORIES = ["Formal Shoes", "Boots", "Athletic", "Oxfords", "Loafers", "Sneakers", "Slippers", "Flats"]

  MENS_SHOE_BRANDS = ["Andrew Marc", "ASICS", "Baffin", "Base London", "Ben Sherman", "Bruno Magli", "Clarks", "Cole Haan", "Donald J Pliner", "Dr. Martens", "Dune London", "French Connection", "Hugo Boss", "Hunter", "JOE'S Jeans", "John Varvatos", "Kenneth Cole", "New Balance", "On Running", "Dr. Scholl’s Collection", "Original Penguin", "Pajar", "PUMA", "Reebok", "Robert Graham", "Rockport", "Salvatore Ferragamo", "Saucony", "Sperry", "The Kooples", "Timberland", "Tod's", "Tommy Bahama", "Vince", "Woolrich", "OTHER "]

  MENS_SHOE_MATERIALS = ["Canvas", "Leather ", "Faux Leather", "Suede", "OTHER"]

  MENS_SHOE_SIZES = ["6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12", "12.5", "13", "13.5", "14", "14.5", "15", "OTHER"]

  MENS_SHOE_WIDTH = ["Narrow", "Medium/Standard", "Wide"]

  COLORS = ["Brown", "Black", "Red", "Pink", "Blue", "White", "Green", "Beige", "Orange", "Yellow", "Purple", "Grey", "Multicolor", "Metallic", "OTHER "]

  def is_not_suit?
    return true unless category == "Suits"
    false
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_owner?, only: [:edit, :update, :destroy]

  def index
    @items = current_user.items.order(updated_at: :desc)
  end

  def show
    @item = Item.find(params[:id])
    @images = ImageUpload.find(@item.image_upload_id).product_images
  end

  def new
    redirect_to new_product_image_path unless params[:image_upload_id]
    @item = Item.new
    @images ||= ProductImage.where(image_upload_id: params[:image_upload_id])
  end

  def create
    @item = current_user.items.create(item_params)
    if @item.save
      ImageUpload.find(@item.image_upload_id).product_images.update_all(item_id: @item.id)
      redirect_to items_path
    else
      render :new, :status => :unprocessable_entity
    end
  end

  def edit
    @item = Item.find(params[:id])
    @images ||= ProductImage.where(image_upload_id: @item.image_upload_id)
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    if @item.save
      flash[:success] = "Item updated."
      redirect_to items_path
    else
      flash[:danger] = "Woops, looks like something went wrong. Please try again."
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    flash[:danger] = "Item deleted"
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:user_id, :brand, :type, :color, :size, :material, :condition, :description, :category, :image_upload_id, :alterations, :gender, :sleeve_length, :inseam_length, :suit_length, :shoe_width, :sub_category, :jacket_size, :pants_size)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_card.html.erb
<div class="row">
  <div class="col-xs-12 col-md-6">
    <div class="panel">
      <div class="panel-body">
        <ul class="no_bullets">
          <li><strong>Brand:</strong> <%= item.brand %></li>
          <li><strong>Category:</strong> <%= item.category %></li>
          <% unless item.sub_category.empty? %>
            <li><strong>Sub Category:</strong> <%= item.sub_category %></li>
          <% end %>
          <li><strong>Color:</strong> <%= item.color %></li>
        </ul>
      </div>
      <!-- panel-body -->
    </div>
    <!-- panel -->
  </div>
  <!-- col-xs-12 col-md-6 -->

  <div class="col-xs-12 col-md-6">
     <div class="panel">
      <div class="panel-body">
        <ul class="no_bullets">
          <% unless item.size.empty? %>
            <li><strong>Size:</strong> <%= item.size %></li>
          <% end %>
          <% unless item.sleeve_length.empty? %>
            <li><strong>Sleeve Length:</strong> <%= item.sleeve_length %></li>
          <% end %>
          <% unless item.inseam_length.empty? %>
            <li><strong>Inseam Length:</strong> <%= item.inseam_length %></li>
          <% end %>
          <% unless item.suit_length.empty? %>
            <li><strong>Suit Length:</strong> <%= item.suit_length %></li>
          <% end %>
          <% unless item.jacket_size.empty? %>
            <li><strong>Jacket Size:</strong> <%= item.jacket_size %></li>
          <% end %>
          <% unless item.pants_size.empty? %>
            <li><strong>Pants Size:</strong> <%= item.pants_size %></li>
          <% end %>
          <% unless item.shoe_width.empty? %>
            <li><strong>Shoe Width:</strong> <%= item.shoe_width %></li>
          <% end %>
          <li><strong>Material:</strong> <%= item.material %></li>
          <li><strong>Condition:</strong> <%= item.condition %></li>
          <!-- <li><strong>Description:</strong> <%= item.description %></li> -->
        </ul>
      </div>
      <!-- panel-body -->
    </div>
    <!-- panel -->
  </div>
  <!-- col-xs-12 col-md-6 -->
</div>
<!-- row -->

app/views/items/edit.html.erb
<div class="well">
  <div class="row">
    <div class="col-xs-12">
      <h1>Item Photos</h1>
      <%= link_to '<i class="fa fa-plus-circle"></i> Add/Delete Photos'.html_safe, edit_product_image_path(image_upload_id: @item.image_upload_id) %>
    </div>
    
    <hr class="clearfix">
    <% if @images %>
      <% @images.each do |image| %>
        <div class="col-xs-12 col-md-3">
          <%= image_tag image.photo.thumb.url, class: 'square item_image', style: 'padding-bottom: 0px' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<h1>Edit Details</h1>

<%= simple_form_for @item, method: :put do |f| %>
  <%= f.input :gender, collection: Item::GENDERS %>
  <%= f.input :category, collection: Item::MENS_CATEGORIES %>
  <%= f.input :sub_category, collection: ["N/A"], include_blank: true %>
  <%= f.input :brand, collection: Item::MENS_APPAREL_BRANDS, include_blank: true %>
  <%= f.input :size, collection: Item::MENS_SHIRT_SIZES, include_blank: true %>
  <%= f.input :jacket_size, collection: Item::MENS_JACKET_SIZES, include_blank: true %>
  <%= f.input :pants_size, collection: Item::MENS_PANTS_SIZES, include_blank: true %>
  <%= f.input :sleeve_length, collection: Item::MENS_SLEEVE_LENGTH, include_blank: true %>
  <%= f.input :inseam_length, collection: Item::MENS_INSEAM_LENGTH, include_blank: true %>
  <%= f.input :suit_length, collection: Item::MENS_SUIT_LENGTH, include_blank: true %>
  <%= f.input :shoe_width, collection: Item::MENS_SHOE_WIDTH, include_blank: true %>
  <%= f.input :color, collection: Item::COLORS %>
  <%= f.input :material, collection: Item::MENS_APPAREL_MATERIALS %>
  <%= f.input :condition, collection: Item::CONDITION %>
  <%= f.input :alterations %>
  <%= f.input :description %>
  <%= f.submit 'Submit', class: 'btn btn-success btn-lg btn-block', data: { disable_with: "Submitting..." } %>
<% end %>
<br>
<%= link_to 'Cancel', item_path(@item), class: 'btn btn-danger btn-lg btn-block' %>

<%= render partial: 'items/form' %>

<script type="text/javascript">
prepopulate();

function prepopulate(){
  
  if (!isMens()){
    $("#item_category").html(womens_categories);
  }

  var pre_selected = $('#item_category option:selected').text();
  if(pre_selected == "Shoes" && isMens()){
      $("label[for=item_sub_category], #item_sub_category").show();
      $("#item_sub_category").html(mens_shoe_categories);
      $("#item_brand").html(mens_shoe_brands);
      $("#item_material").html(mens_shoe_materials);
      $("#item_size").html(mens_shoe_sizes);
      $("label[for=item_shoe_width], #item_shoe_width").show();
  } else if(pre_selected == "Shoes" && !isMens()){
      $("label[for=item_sub_category], #item_sub_category").show();
      $("#item_sub_category").html(womens_shoe_categories);
      $("#item_brand").html(womens_shoe_brands);
      $("#item_material").html(womens_shoe_materials);
      $("#item_size").html(womens_shoe_sizes);
  } else if(pre_selected == "Bags" && !isMens()) {
      $("label[for=item_sub_category], #item_sub_category").show();
      $("#item_sub_category").html(womens_bag_categories);
      $("#item_brand").html(womens_handbag_brands);
  } else if (pre_selected == "Shirts" && isMens()){
      $("#item_size").html(mens_shirt_sizes);
      $("label[for=item_sleeve_length], #item_sleeve_length").show();
      $("#item_brand").html(mens_apparel_brands);
      $("#item_material").html(mens_apparel_materials);
  } else if(pre_selected == "Pants" && isMens()) {
      $("#item_size").html(mens_pants_sizes);
      $("label[for=item_inseam_length], #item_inseam_length").show();
      $("#item_brand").html(mens_apparel_brands);
       $("#item_material").html(mens_apparel_materials);
  } else if((pre_selected == "Outerwear" || pre_selected == "Sport Coat") && isMens()) {
      $("#item_size").html(mens_jacket_sizes);
      $("#item_brand").html(mens_apparel_brands);
      $("#item_material").html(mens_apparel_materials);
  } else if(pre_selected == "Suits" && isMens()) {
      $("#item_size").val('');
      $("label[for=item_size], #item_size").hide();
      $("label[for=item_inseam_length], #item_inseam_length").show();
      $("label[for=item_suit_length], #item_suit_length").show();
      $("label[for=item_jacket_size], #item_jacket_size").show();
      $("label[for=item_pants_size], #item_pants_size").show();
      $("#item_brand").html(mens_apparel_brands);
      $("#item_material").html(mens_apparel_materials);
  } else if(pre_selected == "Suits" && !isMens()) {
      $("#item_size").val('');
      $("label[for=item_size], #item_size").hide();
      $("label[for=item_inseam_length], #item_inseam_length").show();
      $("label[for=item_suit_length], #item_suit_length").show();
      $("label[for=item_jacket_size], #item_jacket_size").show();
      $("label[for=item_pants_size], #item_pants_size").show();
      $("#item_brand").html(womens_apparel_brands);
      $("#item_material").html(womens_apparel_materials);
  } else if(isMens()) {
      $("#item_size").html(mens_shirt_sizes);
      $("#item_brand").html(mens_apparel_brands);
      $("#item_material").html(mens_apparel_materials);
  } else {
      $("#item_brand").html(womens_apparel_brands);
      $("#item_material").html(womens_apparel_materials);
      $("#item_size").html(womens_sizes);
  }
  
}


</script>

app/views/items/index.html.erb
<h1>My Items</h1>
<%= link_to ('<i class="fa fa-plus-circle"></i> Add New Item').html_safe, new_item_path %>
<hr>

<div class="scrollable">
  <div class="list-group">

    <% @items.each do |item| %>
      
      <div class="list-group-item" id = "item_<%= item.id %>">
        <div class="row">
          <div class="col-xs-4 col-sm-2">
            <div class="thumbnail">
              <% if item.product_images.empty? %>
                <%= image_tag 'shirt.png', class: 'item_image_sm' %>
              <% else %>
                <%= image_tag ProductImage.find_by(item_id: item.id).photo.thumb.url %>
              <% end %>
            </div>
          </div>

          <div class="col-xs-8 col-sm-10">
            <%= render partial: "items/card", locals: {item: item} %>

            <span class="pull-right">
              <%= link_to '<i class="fa fa-plus-circle"></i> Add New Photo'.html_safe, edit_product_image_path(id: 1, image_upload_id: item.image_upload_id), style: "margin-right: 10px" %>
              <%= link_to '<i class="fa fa-chevron-circle-right"></i> Details'.html_safe, item_path(item), style: "margin-right: 10px" %>
              <%= link_to '<i class="fa fa-pencil-square-o"></i> Edit'.html_safe, edit_item_path(item), style: "margin-right: 10px" if item.user_id == current_user.id %> 
              <%= link_to '<i class="fa fa-trash-o"></i> Delete'.html_safe, item_path(item), method: :delete, data: { confirm: "Are you sure?" } %>
            </span>
            
          </div>
          <!-- col-xs-10 -->
        </div>
        <!-- row -->
      </div>
      <!-- list-group-item -->

      <script type="text/javascript">
        // $("#item_<%= item.id %>").click(function(){
        //    window.location = "/items/<%= item.id %>";
        // });

        // $('.list-group-item').hover(function(){
        //   $(this).toggleClass('active');
        // });

      </script>

    <% end %>

  </div>
</div>

app/views/items/new.html.erb
<div class="well">
  <div class="row">
    <div class="col-xs-12"><h1>Item Photos</h1></div>
    <% if @images %>
      <% @images.each do |image| %>
        <div class="col-xs-12 col-md-3">
          <%= image_tag image.photo.thumb.url, class: 'square item_image', style: 'padding-bottom: 0px' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<h1>Enter Details</h1>

<%= simple_form_for @item do |f| %>
  <%= f.input :gender, collection: Item::GENDERS %>
  <%= f.input :category, collection: Item::MENS_CATEGORIES %>
  <%= f.input :sub_category, collection: Item::MENS_SHOE_CATEGORIES, include_blank: true %>
  <%= f.input :brand, collection: Item::MENS_APPAREL_BRANDS, include_blank: true %>
  <%= f.input :size, collection: Item::MENS_SHIRT_SIZES, include_blank: true %>
  <%= f.input :jacket_size, collection: Item::MENS_JACKET_SIZES, include_blank: true %>
  <%= f.input :pants_size, collection: Item::MENS_PANTS_SIZES, include_blank: true %>
  <%= f.input :sleeve_length, collection: Item::MENS_SLEEVE_LENGTH, include_blank: true %>
  <%= f.input :inseam_length, collection: Item::MENS_INSEAM_LENGTH, include_blank: true %>
  <%= f.input :suit_length, collection: Item::MENS_SUIT_LENGTH, include_blank: true %>
  <%= f.input :shoe_width, collection: Item::MENS_SHOE_WIDTH, include_blank: true %>
  <%= f.input :color, collection: Item::COLORS %>
  <%= f.input :material, collection: Item::MENS_APPAREL_MATERIALS, include_blank: true %>
  <%= f.input :condition, collection: Item::CONDITION %>
  <%= f.input :alterations %>
  <%= f.input :description %>
  <%= f.input :image_upload_id, as: :hidden, input_html: { value: params[:image_upload_id] } %>
  <%= f.submit 'Submit', class: 'btn btn-success btn-lg btn-block', data: { disable_with: 'Please wait...' } %>
<% end %>

<br>

<%= link_to 'Cancel', dashboard_path, class: 'btn btn-danger btn-lg btn-block' unless params[:image_upload_id] %>
<%= link_to 'Cancel', image_upload_path(params[:image_upload_id]), method: :delete, class: 'btn btn-danger btn-lg btn-block', data: {confirm: "Are you sure?"} if params[:image_upload_id] %>

<%= render partial: 'items/form' %>

app/views/items/show.html.erb
<div class="well">
  <%= link_to '<i class="fa fa-arrow-circle-left"></i> All Items'.html_safe, items_path %>
  <h1>Item Details</h1>

  <div class="row">
    <% @images.each do |images| %>
      <div class="col-xs-4">
        <div class="thumbnail">
            <% if @images.empty? %>
              <%= image_tag 'shirt.png', class: 'item_image' %>
            <% else %>
              <%= image_tag images.photo.thumb.url, class: 'item_image' %>
            <% end %>
          </div>
      </div>
    <% end %>
  </div>
  <br>
  <% if @item.user_id == current_user.id %>
    <%= link_to '<i class="fa fa-plus-circle"></i> Add/Delete Photos'.html_safe, edit_product_image_path(image_upload_id: @item.image_upload_id) %>
    <span class="pull-right">
      <%= link_to '<i class="fa fa-pencil-square-o"></i> Edit'.html_safe, edit_item_path(@item) %>
      <%= link_to '<i class="fa fa-trash-o"></i> Delete'.html_safe, item_path(@item), method: :delete, data: { confirm: "Are you sure?" } %>
    </span>
  <% end %>
  <hr>

  <%= render partial: 'card', locals: {item: @item} %>

  
  <br class="clearfix">
</div>