config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, controllers: {registrations: 'registrations'}

  root 'static_pages#index'

  get 'dashboard' => 'dashboard#index'

  resources :items
  resources :product_images

  resources :image_uploads, only: :destroy

  resources :item_selections, only: [:new, :create]
  resources :company_selections, only: [:new, :create]

  resources :appointment_requests do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :companies
  resources :appointment_approvals, only: :create
  resources :appointment_declinals, only: :create

  resources :charges

  resources :company_users, only: [:new, :create]

  resources :item_statuses, only: :update

  resources :users, only: :show

  get 'privacy_policy' => 'static_pages#privacy_policy'
  get 'terms_and_conditions' => 'static_pages#terms_and_conditions'
  

end

app/views/layouts/_below_carousel.html.erb
<div class="section" id="learn">

  <div class="container">

    <div class="row" style="margin: 50px 0px 50px 0px;">
      <h1 class="text-center" style="font-family: 'pacificoregular'">Stores</h1>
      <hr>
      <div class="col-xs-12">
        <h1 class="text-center" style="font-weight:200">WOULD YOU LIKE TO...</h1>
      </div>
      <br>
    </div>

    <div class="row">
      <div class="col-md-4 col-sm-4">
        <div class="block-icon">
          <i class="fa fa-rocket"></i>
        </div>

        <div class="block-body">
          <h2>Increase Your Acceptance Rates?</h2>
          <div class="line-subtitle"></div>
          <p>
            Pre-screen items and indicate interest before the customer visits your store.
          </p>
        </div>
      </div>
      <div class="col-md-4 col-sm-4">
        <div class="block-icon">
          <i class="fa fa-users"></i>
        </div>

        <div class="block-body">
          <h2>Handle Appointments More Effectively?</h2>
          <div class="line-subtitle"></div>
          <p>
            Schedule appointments electronically and provide customers with available times.
          </p>
        </div>
      </div>
      <div class="col-md-4 col-sm-4">
        <div class="block-icon">
          <i class="fa fa-info-circle"></i>
        </div>

        <div class="block-body">
          <h2>Provide Consignors with Status Updates?</h2>
          <div class="line-subtitle"></div>
          <p>
            Let your consignors know the status of their consigned items and when payment is available.
          </p>
        </div>
      </div>
    </div><!-- /.row -->
    
    <div class="row" style="margin: 100px 0px 50px 0px;">
      <h1 class="text-center" style="font-family: 'pacificoregular'">Consignors</h1>
      <hr>
      <div class="col-xs-12">
        <h1 class="text-center" style="font-weight:200">WOULD YOU LIKE TO...</h1>
      </div>
      <br>
    </div>

    <div class="row">
      <div class="col-md-4 col-sm-4">
        <div class="block-icon">
          <i class="fa fa-check-square-o"></i>
        </div>

        <div class="block-body">
          <h2>Have Your Consignment Items Pre-screened?</h2>
          <div class="line-subtitle"></div>
          <p>
            Know exactly which items to take your favorite consignment store.
          </p>
        </div>
      </div>
      <div class="col-md-4 col-sm-4">
        <div class="block-icon">
          <i class="fa fa-calendar-check-o"></i>
        </div>

        <div class="block-body">
          <h2>Schedule Appointments Online for Item Review?</h2>
          <div class="line-subtitle"></div>
          <p>
            Request an appointment time to have your belongings evaluated.
          </p>
        </div>
      </div>
      <div class="col-md-4 col-sm-4">
        <div class="block-icon">
          <i class="fa fa-pencil"></i>
        </div>

        <div class="block-body">
          <h2>Keep Track of Your Items and Appointments?</h2>
          <div class="line-subtitle"></div>
          <p>
            Know at a glance which stores you have consigned items and appointments.
          </p>
        </div>
      </div>
    </div><!-- /.row -->

  </div><!-- /.container -->

</div><!-- /.section -->

<!--
<div class="section-colored home">

  <div class="container">

    <div class="row">
      <div class="col-md-9 col-sm-8">
        <h2 style="color:white; font-weight:200">We are inviting a limited number of retailers to participate in our pre-launch group. If you are interested in being a part of this exclusive group and would like to learn more, let’s connect!</h2>
      </div>
      <div class="col-md-3 col-sm-4">
        <a href="#" class="btn btn-danger btn-lg"><i class="fa fa-hand-o-right"></i> Let's Connect</a>
      </div>
    </div>

  </div>

</div>
-->

app/views/layouts/_carousel.html.erb
<div id="blur_parent">
  <div id="blur_image">
  </div>

  <div class="image_text_wrapper">
    <div class="image_text">

      <!-- flash messages -->
      <% flash.each do |message_type, message| %>
        <% if message_type == "notice" %>
          <div class="alert alert-info alert-dismissible"><%= notice %></div>
        <% elsif message_type == "alert" %>
          <div class="alert alert-danger alert-dismissible"><%= alert %></div>
        <% else %>
          <div class="alert alert-<%= message_type %> alert-dismissible"><%= message %></div>
        <% end %>
      <% end %>

      <div id="image_content">
        <%= image_tag 'logo_text.png', style: "height: 60px; display:block; margin: 0 auto;" %>
        <span id="copy_h1">
        </span>

        <br><br>
        <div class="btn btn-lg btn-danger btn-fixed" id ="sign_up">Sign Up</div>
<!--           <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-lg btn-danger btn-fixed' %> -->          
        <%= link_to 'Log In', new_user_session_path, class: 'btn btn-lg btn-success btn-fixed' %>
        <h1 style="visibility:hidden">Simplifying Consignment.</h1>
      </div>

      <div id="sign_up_options">
        <h1 style="font-family: 'pacificoregular'">I am a</h1>
        <hr>
        <%= link_to 'Consignor', new_user_registration_path, class: 'btn btn-lg btn-primary btn-fixed' %>
        <%= link_to 'Store', new_company_user_path, class: 'btn btn-lg btn-danger btn-fixed' %>
        <br>
        <br>
        <p>or <%= link_to 'Log In', new_user_session_path, style: 'color: white; text-decoration: underline;' %></p>
      </div>
      <!-- sign_up_options -->
    </div>
    <!-- image_text -->
  </div>
  <!-- image_text_wrapper -->
</div>

app/views/layouts/_dashboard_nav.html.erb
<ul class="nav nav-pills" style="margin-bottom:30px;">
  <li role="presentation"><%= link_to 'Home', dashboard_path %></li>

  <% if current_user.is_company_account? && current_user.company_id %>
    <li role="presentation"><%= link_to "My Company", companies_path(current_user.company_id) %></li>
  <% elsif !current_user.is_company_account? %>
    <li role="presentation"><%= link_to 'My Items', items_path %></li>
  <% end %>

  <li role="presentation"><%= link_to 'My Appointments', appointment_requests_path %></li>
  <li role="presentation"><%= link_to 'My Profile', user_path(current_user.id) %></li>
  
</ul>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">

    <div class="row">
      <div class="col-lg-3 col-md-3">
        <a class="footer-brand" href="/"><%= image_tag 'logo.png', class: "footer_logo" %></a>
        
        
      </div>
      <div class="col-lg-3 col-md-3">
        <h3>CONTACT</h3>
        <address>
          <strong>äLuxuRē</strong><br>
          <i class="fa fa-map-marker"></i> P.O. Box110152<br>Durham, NC 27709<br>
          <!-- <i class="fa fa-phone"></i> (123) 456-7890<br> -->
          <i class="fa fa-envelope"></i> connect@aluxurelife.com
        </address>
      </div>
      
      <div class="col-lg-3 col-md-3">
        <h3>LATEST TWEETS</h3>
        <ul class="latest-tweets">
          <% $client.user_timeline("a_LuxuRe").each_with_index do |tweet, i| %>
            <% if i < 2 %>
              <li>
                <i class="fa fa-twitter"></i> <%= tweet.text %>
              </li>
            <% end %>
            <!-- if i < 2 -->
          <% end %>
          <!-- each_with_index -->
        </ul>
      </div>

      <div class="col-lg-3 col-md-3">
        <h3>FIND US</h3>
        <ul class="list-inline list-unstyled social-networks">
          <!-- <li>
            <a href="#">
              <div class="icon-social icon-social-facebook normal">
                <i class="fa fa-facebook"></i>
              </div>
              <div class="icon-social hover">
                <i class="fa fa-facebook"></i>
              </div>
            </a>
          </li> -->

          <li>
            <a href="https://twitter.com/a_LuxuRe">
              <div class="icon-social icon-social-twitter normal">
                <i class="fa fa-twitter"></i>
              </div>
              <!-- <div class="icon-social hover">
                <i class="fa fa-twitter"></i>
              </div> -->
            </a>
          </li>

          <!-- <li>
            <a href="#">
              <div class="icon-social icon-social-google-plus normal">
                <i class="fa fa-google-plus"></i>
              </div>
              <div class="icon-social hover">
                <i class="fa fa-google-plus"></i>
              </div>
            </a>
          </li> -->

          <!-- <li>
            <a href="https://www.youtube.com/channel/UCBMeC054Dra12ncD2aqs4Ow">
              <div class="icon-social icon-social-youtube normal">
                <i class="fa fa-youtube-play"></i>
              </div>
              <div class="icon-social hover">
                <i class="fa fa-youtube-play"></i>
              </div>
            </a>
          </li> -->

          <li>
            <a href="https://www.linkedin.com/company/%C3%A4luxur%C4%93">
              <div class="icon-social icon-social-linkedin normal">
                <i class="fa fa-linkedin"></i>
              </div>
             <!--  <div class="icon-social hover">
                <i class="fa fa-linkedin"></i>
              </div> -->
            </a>
          </li>

          <li>
            <a href="https://www.pinterest.com/luxur1550/consigning-tips/">
              <div class="icon-social icon-social-pinterest normal">
                <i class="fa fa-pinterest"></i>
              </div>
              <!-- <div class="icon-social hover">
                <i class="fa fa-pinterest"></i>
              </div> -->
            </a>
          </li>
        </ul>
        <!-- <h3>NEWSLETTER</h3>
        <p>Type your email address below and subscribe to our newsletter</p>
        <div class="input-group">
          <input type="text" placeholder="Email" class="form-control">
          <span class="input-group-btn">
            <button class="btn btn-primary" type="button">Go!</button>
          </span>
        </div> -->
      </div>
    </div><!-- /.row -->

  </div><!-- /.container -->
</footer>

<div class="footer-after">
  <div class="container">
    <div class="row">
      <div class="col-md-10">
        <p>Copyright © 2015 – Present Copula Systems, LLC</p>
        <p>äLuxuRē and aluxurelife.com are service marks of Copula Systems, LLC</p>
      </div>
      <div class="col-md-2">
        <p class="legal"><a href="/privacy_policy" rel="nofollow" style="text-decoration: underline;">Privacy Policy</a></p>
        <p class="legal"><a href="/terms_and_conditions" rel="nofollow" style="text-decoration: underline;">Terms and Conditions</a></p>
      </div>
    </div><!-- /.row -->
  </div>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-73604255-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="/"><%= image_tag 'logo.png', class: "logo" %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a href="/">Home</a></li>
          <li><%= link_to 'My Appointments', appointment_requests_path %></li>
          <li><%= link_to 'My Items', items_path unless current_user.company_id %></li>
          <li><%= link_to 'Settings', edit_user_registration_path %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><a href="/#top">Home</a></li>
          <li><a href="/#learn">Learn More</a></li>
          <li><a href="/#about">About</a></li>
          <li><a href="/#top" id="sign_up_nav">Sign Up</a></li>
          <li><%= link_to 'Log In', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/_recent_projects.html.erb
<!-- <div class="section" id="recent-projects" style="position: relative;">

  <div class="container">

    <div class="row">
      <div class="col-lg-12">
        <h1 class="text-center" style="margin-bottom:50px">Services</h1>
      </div>


      <div class="col-md-3 col-sm-3">
        <div class="block-icon">
          <i class="fa fa-users"></i>
        </div>

        <div class="block-body">
          <h2>Enhance Customer Experience</h2>
          <div class="line-subtitle"></div>
          <p>Digitize your store to enable customers to find the right product at the right time.</p>
        </div>
      </div>
      <div class="col-md-3 col-sm-3">
        <div class="block-icon">
          <i class="fa fa-bar-chart"></i>
        </div>

        <div class="block-body">
          <h2>Know Business Insights</h2>
          <div class="line-subtitle"></div>
          <p>Trend your business and your market to guide mission-critical decisions. Monitor product, pricing, seasonal, and customer analytics.</p>
        </div>
      </div>
      <div class="col-md-3 col-sm-3">
        <div class="block-icon">
          <i class="fa fa-expand"></i>
        </div>

        <div class="block-body">
          <h2>Expand Customer Reach</h2>
          <div class="line-subtitle"></div>
          <p>Broaden your market share by extending your control of supply and demand, virtually.</p>
        </div>
      </div>
      <div class="col-md-3 col-sm-3">
        <div class="block-icon">
          <i class="fa fa-paper-plane"></i>
        </div>

        <div class="block-body">
          <h2>Streamline Operations</h2>
          <div class="line-subtitle"></div>
          <p>Automate buying, selling, and logistical workflows</p>
        </div>
      </div>

    </div><!-- /.row -->

  </div><!-- /.container -->

</div><!-- /.section -->



<div class="section-colored" id="about">

  <div class="container">
    <h1 class="text-center" style="font-family: 'pacificoregular'">About</h1>
    <hr>
    <div class="container clients">

      <div class="row">
        <p class="lead">
          äLuxuRē simplifies the consignment process. Our mobile app/web solution allows sellers and consignment stores to engage each other in a way that eliminates many of the frustrations encountered during the consignment process resulting in improved productivity and a better customer experience. 
        </p>
        <!-- <div style="text-align: center;">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/wzduCFxXfm4"></iframe>
          </div>
       </div> -->
      </div><!-- /.row -->

    </div><!-- /.container -->

  </div><!-- /.container -->

</div><!-- /.section-colored -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>äLuxuRē | Simplifying Consignment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

  <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
  <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
  <link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
  <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
  <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="msapplication-TileImage" content="/mstile-144x144.png">
  <meta name="theme-color" content="#ffffff">

</head>
<body>

<%= render 'layouts/nav' %>

<div class="container">
  <div class="content">

    <% flash.each do |message_type, message| %>
      <% if message_type == "notice" %>
        <p class="alert alert-info alert-dismissible"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= notice %></p>
      <% elsif message_type == "alert" %>
        <p class="alert alert-danger alert-dismissible"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= alert %></p>
      <% else %>
        <div class="alert alert-<%= message_type %> alert-dismissible"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= message %></div>
      <% end %>
    <% end %>

    <%= render 'layouts/dashboard_nav' if user_signed_in? %>

    <%= yield %>

  </div>
</div>


<%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/landing_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>äLuxuRē | Simplifying Consignment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body id="top">

<%= render 'layouts/nav' %>

<%= render 'layouts/carousel' %>

<%= render 'layouts/below_carousel' %>

<%= render 'layouts/recent_projects' %>

<%= render 'layouts/footer' %>

<script type="text/javascript">

$(function() {
  $('a[href*="#"]:not([href="#"])').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
      var target = $(this.hash);
      target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
      if (target.length) {
        $('html, body').animate({
          scrollTop: target.offset().top
        }, 1000);
        return false;
      }
    }
  });
});

$(function() {
  $('nav a[href^="/' + location.pathname.split("/")[1] + '"]').addClass('active');
});

$("#sign_up, #sign_up_nav").on("click", function(){
  $("#image_content").fadeOut(800);
  setTimeout(function(){
    $("#sign_up_options").fadeIn("slow");
  }, 800);
});

$(function(){
    $("#copy_h1").typed({
        strings: ["Simplifying Consignment."],
        typeSpeed: 40
    });
});

</script>

</body>
</html>